export const ANSWERS = ['HELLO','WORLD','QUITE','FANCY','FRESH','PANIC','CRAZY','BUGGY','SCARE','SWEET','BREAD','APPLE','GRAPE','LEMON','PEACH','PLUMS','CHERRY','MANGO','KIWI','BERRY','PEAR','ORANGE','BANAN','TIGER','LION','BEARS','WOLFS','SHARKS','WHALE','DOLPH','FISHY','OCEAN','RIVER','LAKEY','MOUNT','HILLS','VALLE','CLOUDS','RAINY','SUNNY','STORMY','SNOWY'];
export const ALLOWED = ANSWERS;
